### ISSUE TITLE
Micrsoft Bot Framework - doesn't run

### ISSUE THREAD

**Issue by sirtimbly** [Botanalyticsco/botanalytics#3]
Installed from NPM. When I run my node app locally it fails because `util` is undefined inside microsoft.js

Console output follows.

```
/Users/tim/Sites/GoHealthHeroBot-src/node_modules/botanalytics/platforms/microsoft.js:22
  log.debug('Configuration: ' + util.inspect(config))
                                ^
ReferenceError: util is not defined
    at Object.module.exports [as MicrosoftBotFramework] (/Users/tim/Sites/GoHealthHeroBot-src/node_modules/botanalytics/platforms/microsoft.js:22:33)
    at Object.<anonymous> (/Users/tim/Sites/GoHealthHeroBot-src/build/app.js:24:5)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Waiting for the debugger to disconnect...
ReferenceError: util is not defined
microsoft.js:22
    at Object.module.exports [as MicrosoftBotFramework] (/Users/tim/Sites/GoHealthHeroBot-src/node_modules/botanalytics/platforms/microsoft.js:22:33)
    at Object.<anonymous> (/Users/tim/Sites/GoHealthHeroBot-src/build/app.js:24:5)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
And that checks out for me if I [look at the code](https://github.com/Botanalyticsco/botanalytics/blob/851a6d41e2c91644099aaf69ae64d2615af17cb0/platforms/microsoft.js#L22) I can't see how it would be working.

**Comment by BeyhanEsen** [comment]
Thank you @sirtimbly for letting us know, it's fixed in v2.4.1.
